# Generated by Django 4.2.5 on 2024-02-15 22:08

from django.core.management import call_command
from django.db import migrations


def create_primary_song_catalog(apps, schema_editor):
    SongCatalog = apps.get_model("song_api", "SongCatalog")
    User = apps.get_model("auth", "User")  # Import the User model
    user = User.objects.get(pk=1)
    SongCatalog.objects.create(
        pk=1, song_catalog_name="Default", song_catalog_owner=user
    )


def drop_primary_song_catalog(apps, schema_editor):
    SongCatalog = apps.get_model("song_api", "SongCatalog")
    SongCatalog.objects.filter(pk=1).delete()


def load_initial_songs(apps, schema_editor):
    call_command("loaddata", "song_api/initial_songs.json", verbosity=2)


def clear_initial_songs(apps, schema_editor):
    Song = apps.get_model("song_api", "Song")
    Song.objects.filter(pk__range=(1, 2881)).delete()


class Migration(migrations.Migration):
    dependencies = [("song_api", "0001_initial"), ("user_management", "0001_initial")]

    operations = [
        migrations.RunPython(create_primary_song_catalog, drop_primary_song_catalog),
        migrations.RunPython(load_initial_songs, clear_initial_songs),
    ]
