# Generated by Django 4.2.5 on 2023-11-12 17:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("song_api", "0006_remove_song_clonehero_a_search__407b54_gin_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="song",
            name="clonehero_a_search__e10779_gin",
        ),
        migrations.RemoveField(
            model_name="song",
            name="search_vector_upd",
        ),
        migrations.AddField(
            model_name="song",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="song",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="clonehero_a_search__407b54_gin"
            ),
        ),
    ]
