# Generated by Django 4.2.5 on 2023-11-29 15:52

import django.contrib.postgres.search
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("song_api", "0007_remove_song_clonehero_a_search__e10779_gin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="create_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="song",
            name="update_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
    ]
