# Generated by Django 4.2.5 on 2023-12-25 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("song_api", "0008_song_create_date_song_update_date_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="song",
            new_name="song_api_so_search__cbc7fe_gin",
            old_name="clonehero_a_search__407b54_gin",
        ),
    ]
