# Generated by Django 4.2.5 on 2023-12-25 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("song_api", "0010_songcatalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="song_catalog",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="song_api.songcatalog",
            ),
            preserve_default=False,
        ),
    ]
