# Generated by Django 4.2.5 on 2024-01-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("song_api", "0011_song_song_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="album",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="charter",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="genre",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_bass",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_bassghl",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_drums",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_drums_real",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_guitar",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_guitar_coop",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_guitar_coop_ghl",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_guitarghl",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_keys",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_rhythm",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_rhythm_ghl",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="song_length",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
