# Generated by Django 4.2.5 on 2024-02-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "song_api",
            "0012_alter_song_album_alter_song_charter_alter_song_genre_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="intensity_bass_real",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="intensity_drums_phase_shift",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="intensity_guitar_real",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="intensity_keys_phase_shift",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="intensity_keys_real",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_bass",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_bassghl",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_drums",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_drums_real",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_guitar",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_guitar_coop",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_guitar_coop_ghl",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_guitarghl",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_keys",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_rhythm",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_rhythm_ghl",
            field=models.IntegerField(
                choices=[
                    (-1, "Not mapped for this instrument"),
                    (0, "Intensity level 0"),
                    (1, "Intensity level 1"),
                    (2, "Intensity level 2"),
                    (3, "Intensity level 3"),
                    (4, "Intensity level 4"),
                    (5, "Intensity level 5"),
                    (6, "Intensity level 6"),
                ],
                default=-1,
            ),
        ),
    ]
