# Generated by Django 4.2.5 on 2023-11-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clonehero_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="intensity_bass",
            field=models.IntegerField(
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_bassghl",
            field=models.IntegerField(
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_drums",
            field=models.IntegerField(
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_drums_real",
            field=models.IntegerField(
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_guitar",
            field=models.IntegerField(
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_guitar_coop",
            field=models.IntegerField(
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_guitar_coop_ghl",
            field=models.IntegerField(
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_guitarghl",
            field=models.IntegerField(
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_keys",
            field=models.IntegerField(
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_rhythm",
            field=models.IntegerField(
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="intensity_rhythm_ghl",
            field=models.IntegerField(
                choices=[
                    (0, "Intensity 0"),
                    (1, "Intensity 1"),
                    (2, "I'm too young to die"),
                    (3, "Hey, not too rough"),
                    (4, "Hurt me plenty"),
                    (5, "Ultra-Violence"),
                    (6, "Nightmare"),
                ]
            ),
        ),
    ]
