# Generated by Django 4.2.5 on 2023-11-12 16:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "clonehero_api",
            "0004_alter_song_album_alter_song_charter_alter_song_genre_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="song",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="clonehero_a_search__407b54_gin"
            ),
        ),
    ]
