# Generated by Django 4.2.5 on 2024-02-15 23:04

from django.db import migrations


def create_initial_event(apps, schema_editor):
    Event = apps.get_model("event_api", "Event")
    Event.objects.create(
        pk=1,
        event_name="Default",
        event_date="2024-02-15",
        create_date="2024-02-15",
        update_date="2024-02-15",
        song_catalog_id=1,
        event_organizer_id=1,
    )


def drop_initial_event(apps, schema_editor):
    Event = apps.get_model("event_api", "Event")
    Event.objects.filter(pk=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("event_api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_event),
    ]
