# Generated by Django 4.2.5 on 2023-11-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_api", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="eventplan",
            constraint=models.UniqueConstraint(
                fields=("event", "song"), name="unique_song_per_event"
            ),
        ),
    ]
