# Generated by Django 4.2.5 on 2023-11-29 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("song_api", "0008_song_create_date_song_update_date_and_more"),
        ("event_api", "0002_eventplan_unique_song_per_event"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventPlan",
            new_name="EventToSongMapping",
        ),
    ]
