# Generated by Django 4.2.5 on 2023-12-06 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event_api", "0004_rename_eventtosongmapping_songateventmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="songateventmapping",
            name="mapper",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="songateventmapping",
            index=models.Index(
                fields=["mapper"], name="event_api_s_mapper__edcc49_idx"
            ),
        ),
    ]
