# Generated by Django 4.2.5 on 2024-02-15 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event_api", "0007_eventattendee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventattendee",
            name="attendee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attended_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
