branch-defaults:
  main:
    environment: probable-journey-single-env
    group_suffix: null
global:
  application_name: probable-journey-single
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: ebdeploy
  repository: null
  sc: git
  workspace_type: Application
environment:
  probable-journey-single-env:
    option_settings:
      - namespace: aws:elasticbeanstalk:environment
        option_name: EnvironmentType
        value: SingleInstance
      - namespace: aws:rds:dbinstance
        option_name: DBInstanceClass
        value: db.t3.micro
      - namespace: aws:rds:dbinstance
        option_name: DBEngine
        value: postgres
      - namespace: aws:rds:dbinstance
        option_name: DBEngineVersion
        value: '16.0'
      - namespace: aws:rds:dbinstance
        option_name: DBAllocatedStorage
        value: '5'
