branch-defaults:
  main:
    environment: probable-journey-dev
    group_suffix: null
global:
  application_name: probable-journey
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: ebdeploy
  repository: null
  sc: git
  workspace_type: Application
